version: '3.8'

services:
  db:
    image: postgres:15
    container_name: xbank_db
    environment:
      POSTGRES_DB: xbank_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: xbank_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    restart: always

volumes:
  db_data:
